name: datahub-actions docker
on:
  push:
    branches:
      - main
    paths-ignore:
      - "build/**"
      - "**.md"
  pull_request:
    branches:
      - main
    paths:
      - "docker/**"
      - ".github/workflows/datahub-actions-docker.yml"
      - "!build/**"
      - "!**.md"
  release:
    types: [published, edited]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      publish: ${{ steps.publish.outputs.publish }}
      # The tracking tag will be "head", "v1.2.3", or "pr1234".
      # The unique tag will be a short SHA.
      unique_tag: ${{ steps.tag.outputs.unique_tag }}
      tracking_tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compute Tag
        id: tag
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          SHORT_SHA=$(git rev-parse --short "$GITHUB_SHA")
          echo "SHORT_SHA: $SHORT_SHA"
          UNIQUE_TAG=$SHORT_SHA
          echo "UNIQUE_TAG: $UNIQUE_TAG"
          TRACKING_TAG=$(echo ${GITHUB_REF} | sed -e "s,refs/heads/main,head,g" -e 's,refs/tags/,,g' -e 's,refs/pull/\([0-9]*\).*,pr\1,g')
          echo "TRACKING_TAG: $TRACKING_TAG"

          echo "unique_tag=$UNIQUE_TAG" >> "$GITHUB_OUTPUT"
          echo "tracking_tag=$TRACKING_TAG" >> "$GITHUB_OUTPUT"
  regular_image:
    name: Build & Push Image to DockerHub
    if: true
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: |
            phuchung276/datahub-actions
          tags: |
            type=raw,value=${{ needs.setup.outputs.unique_tag }}
            type=raw,value=${{ needs.setup.outputs.tracking_tag }},enable=${{ needs.setup.outputs.tracking_tag != '' }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        if: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        if: true
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & Push Image
        uses: docker/build-push-action@v6
        with:
          file: ./docker/datahub-actions/Dockerfile
          platforms: ${{ needs.setup.outputs.publish == 'true' && 'linux/amd64,linux/arm64' || 'linux/amd64' }}
          tags: phuchung276/datahub-actions:head
          push: ${{ needs.setup.outputs.publish == 'true' }}
          cache-from: type=registry,ref=${{ steps.docker_meta.outputs.tags }}
          cache-to: type=inline
          target: final